# **Project Title : "Malaria Surveillance and Predictive Analytics Using Simulated Healthcare Data"**

#### Core Goal: "To clean, analyze, and model malaria-related healthcare data to identify patterns and predict malaria outcomes."

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
df1 = pd.read_csv(r"C:\Users\FRINICT\Documents\Anavami and John Class\Malaria Dataset  Analysis\Malaria Simulation Data\malaria_patient_data.csv")

In [11]:
df1

      patient_id  age    state season mosquito_net owns_tv random_text
0           1000    9    G0mbe    NaN            N     Yes         123
1           1001   25     Ogun    Dry          YES     Yes         NaN
2           1002   68  Anambra  rainy          NaN      No         abc
3           1003  NaN    Abuja    NaN            N     NaN         123
4           1004   49  Plateau  R@iny          YES     Yes         abc
...          ...  ...      ...    ...          ...     ...         ...
4495        5495   40      Imo  Rainy           No      No         abc
4496        5496   68    Delta  Rainy          YES     NaN         123
4497        5497   51    Ekiti  R@iny           no      No         NaN
4498        5498   54   Kaduna    dry           no      No         abc
4499        5499   11    Benue    dry           No      No         NaN

[4500 rows x 7 columns]

In [13]:
# Dataset information
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    4500 non-null   int64
 1   age           4453 non-null   object
 2   state         4500 non-null   object
 3   season        3728 non-null   object
 4   mosquito_net  3850 non-null   object
 5   owns_tv       3063 non-null   object
 6   random_text   3358 non-null   object
dtypes: int64(1), object(6)
memory usage: 246.2+ KB

In [15]:
# Sum of null rows
df1.isnull().sum()

patient_id         0
age               47
state              0
season           772
mosquito_net     650
owns_tv         1437
random_text     1142
dtype: int64

In [19]:
# Dataset columns
df1.columns

Index(['patient_id', 'age', 'state', 'season', 'mosquito_net', 'owns_tv',
       'random_text'],
      dtype='object')

In [21]:
df1.columns.tolist()

['patient_id',
 'age',
 'state',
 'season',
 'mosquito_net',
 'owns_tv',
 'random_text']

In [23]:
# Datatypes of each column
df1.dtypes

patient_id       int64
age             object
state           object
season          object
mosquito_net    object
owns_tv         object
random_text     object
dtype: object

In [27]:
df1["age"].unique()

array(['9', '25', '68', nan, '49', '11', '53', '54', '67', '15', '35',
       '16', '61', '59', '17', '10', '3', '28', '5', '32', '2', '14',
       '60', '8', '50', '48', '66', '62', '56', '72', '-5', '20', '64',
       '57', '31', '40', '39', '45', '19', '65', '75', '18', '73', '69',
       '51', '79', '1', '58', '77', '4', '71', '44', '37', '6', '43',
       '34', '23', '63', '36', '24', '22', '26', '55', '7', '38', '52',
       '46', '13', '21', '74', '78', '41', '29', '??', '12', '30', '27',
       '33', '42', '47', '70', '76'], dtype=object)

In [29]:
df1["state"].unique()

array(['G0mbe', 'Ogun', 'Anambra', 'Abuja', 'Plateau', 'Niger', 'Ondo',
       'Oyo', 'gombe', 'Zamfara', 'Delta', 'Kaduna', 'Nasarawa', 'Enugu',
       'Cross River', 'Borno', 'kogi', 'lagos ', 'Adamawa', 'crossriver',
       'Kwara', 'Benue', 'Ed0o', 'Rivers', 'Abla', 'Bauchi', 'S0koto',
       'Ekiti', 'Imo', 'benue', 'Kano', 'Lagos', 'Kaduba', 'katsina',
       'Bayelsa', 'Taraba', 'Jigawa', 'KAN0', 'Ebonyi', 'Yobe', 'Kebbis',
       '??Rivers', 'Osun'], dtype=object)

In [31]:
df1["state"].nunique()

43

In [33]:
df1["season"].unique()

array([nan, 'Dry', 'rainy', 'R@iny', 'Rainy', 'dry'], dtype=object)

In [35]:
df1["mosquito_net"].unique()

array(['N', 'YES', nan, 'Y', 'no', 'No', 'Yes'], dtype=object)

In [37]:
df1["owns_tv"].unique()

array(['Yes', 'No', nan], dtype=object)

In [39]:
df1["random_text"].unique()

array(['123', nan, 'abc', '@@@'], dtype=object)

In [43]:
df1["season"].value_counts()

season
rainy    760
R@iny    759
Rainy    759
Dry      727
dry      723
Name: count, dtype: int64

In [45]:
df1["mosquito_net"].value_counts()

mosquito_net
N      665
Yes    655
no     653
Y      651
YES    617
No     609
Name: count, dtype: int64

In [47]:
df1["owns_tv"].value_counts()

owns_tv
Yes    1597
No     1466
Name: count, dtype: int64

-------------------------------------------------------------------------------------------------

In [71]:
# another way to approach it
for col in df1.columns:
    unique_vals = df1[col].unique()

    print(f"\n--- {col} ---")
    print(f"Unique count: {len(unique_vals)}")
    print(unique_vals)
    # print(unique_vals[:10])  # first 10 unique values

--- patient_id ---
Unique count: 4500
[1000 1001 1002 ... 5497 5498 5499]

--- age ---
Unique count: 82
['9' '25' '68' nan '49' '11' '53' '54' '67' '15' '35' '16' '61' '59' '17'
 '10' '3' '28' '5' '32' '2' '14' '60' '8' '50' '48' '66' '62' '56' '72'
 '-5' '20' '64' '57' '31' '40' '39' '45' '19' '65' '75' '18' '73' '69'
 '51' '79' '1' '58' '77' '4' '71' '44' '37' '6' '43' '34' '23' '63' '36'
 '24' '22' '26' '55' '7' '38' '52' '46' '13' '21' '74' '78' '41' '29' '??'
 '12' '30' '27' '33' '42' '47' '70' '76']

--- state ---
Unique count: 36
['Gombe' 'Ogun' 'Anambra' 'Abuja' 'Plateau' 'Niger' 'Ondo' 'Oyo' 'Zamfara'
 'Delta' 'Kaduna' 'Nasarawa' 'Enugu' 'Cross River' 'Borno' 'Kogi' 'Lagos'
 'Adamawa' 'Kwara' 'Benue' 'Edo' 'Rivers' 'Abia' 'Bauchi' 'Sokoto' 'Ekiti'
 'Imo' 'Kano' 'Katsina' 'Bayelsa' 'Taraba' 'Jigawa' 'Ebonyi' 'Yobe'
 'Kebbi' 'Osun']

--- season ---
Unique count: 6
[nan 'Dry' 'rainy' 'R@iny' 'Rainy' 'dry']

--- mosquito_net ---
Unique count: 7
['N' 'YES' nan 'Y' 'no' 'No' 'Yes']

--- owns_tv ---
Unique count: 3
['Yes' 'No' nan]

-------------------------------------------------------------------------------------------------
#### Identify Data Quality Problems

#### Problems Detected

#### 1. Missing Values

Columns affected:

```text
* `age`
* `season`
* `mosquito_net`
* `owns_tv`
* `random_text`

```

---

#### 2. Inconsistent State Names in the "state" column

Examples:

```text
"G0mbe"
"gombe"
"Kaduna"
"Kaduba"
"S0koto"
"KAN0"
"Kebbis"
"??Rivers"
"Abla"
"crossriver"
"Ed0o"
"benue"
```

These should become:

```text
"Gombe", "Kaduna", "Sokoto", "Kano", "Kebbi", "Rivers", "Abia", "Cross River", "Edo", "Benue"
```

---

#### 3. Inconsistent "season" Labels

Examples:

```text
rainy
R@iny
Dry
```

Need standardization:

```text
Rainy
Dry
```

---

#### 4. Inconsistent Binary Values for "mosquito_net"


Current values:

```text
"YES"
"Y"
"Yes"
"N"
"no"
"No"
```

Should be: 

```text
"Yes"
"No"
```

---

#### 5. Irrelevant Column `random_text`

Contains:

```text
"123"
"abc"
"@@@"
```

This is noise, unnecessary, useless information and should be removed.

---

#### 6. Data Type Issues

* `age` should be numeric
* categorical columns should be standardized

---

In [52]:
# Dropping the Irrelevant column "random_text"
df1.drop(columns = ["random_text"], inplace = True)

In [54]:
df1.head()

   patient_id  age    state season mosquito_net owns_tv
0        1000    9    G0mbe    NaN            N     Yes
1        1001   25     Ogun    Dry          YES     Yes
2        1002   68  Anambra  rainy          NaN      No
3        1003  NaN    Abuja    NaN            N     NaN
4        1004   49  Plateau  R@iny          YES     Yes

In [56]:
# Standardizing State name in the column "State"
df1['state'] = df1['state'].replace({
    'G0mbe': 'Gombe',
    'gombe': 'Gombe',
    'Kaduba': 'Kaduna',
    'S0koto': 'Sokoto',
    'KANO': 'Kano',
    'KAN0': 'Kano',
    'Kebbis': 'Kebbi',
    '??Rivers': 'Rivers',
    'Abla': 'Abia',
    'crossriver': 'Cross River',
    'Ed0o': 'Edo',
    'benue': 'Benue',
    'lagos': 'Lagos',
    'lagos ': 'Lagos', 
    'kogi': 'Kogi',
    'katsina': 'Katsina',
    
    
})

In [66]:
afstd_1 = df1["state"].unique()
afstd_2 = df1["state"].nunique()

print("We now have each state name standardized as below:", afstd_1, "and the total number of states is :", afstd_2)

We now have each state name standardized as below: ['Gombe' 'Ogun' 'Anambra' 'Abuja' 'Plateau' 'Niger' 'Ondo' 'Oyo' 'Zamfara'
 'Delta' 'Kaduna' 'Nasarawa' 'Enugu' 'Cross River' 'Borno' 'Kogi' 'Lagos'
 'Adamawa' 'Kwara' 'Benue' 'Edo' 'Rivers' 'Abia' 'Bauchi' 'Sokoto' 'Ekiti'
 'Imo' 'Kano' 'Katsina' 'Bayelsa' 'Taraba' 'Jigawa' 'Ebonyi' 'Yobe'
 'Kebbi' 'Osun'] and the total number of states is : 36

In [75]:
# Standardizing Season values in the "season" column
df1['season'] = df1['season'].replace({
    'rainy': 'Rainy',
    'R@iny': 'Rainy',
    'Dry': 'Dry',
    'dry': 'Dry',
})

In [79]:
afstd_3 = df1["season"].unique()
afstd_4 = df1["season"].nunique()
print(afstd_3, afstd_4)

[nan 'Dry' 'Rainy'] 2

In [82]:
# Standardizing the inconsistent binary values for mosquito net
df1['mosquito_net'] = df1['mosquito_net'].replace({
    'YES': 'Yes',
    'Y': 'Yes',
    'N': 'No',
    'no': 'No'
})

In [86]:
afstd_5 = df1["mosquito_net"].unique()
afstd_6 = df1["mosquito_net"].nunique()
print(afstd_5, afstd_6)

['No' 'Yes' nan] 2

In [88]:
# A summary table
summary = pd.DataFrame({
    "column": df1.columns,
    "unique_count": [df1[col].nunique() for col in df1.columns]
})

# print(summary)
summary

         column  unique_count
0    patient_id          4500
1           age            81
2         state            36
3        season             2
4  mosquito_net             2
5       owns_tv             2

In [108]:
df1info = df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    4500 non-null   int64
 1   age           4500 non-null   float64
 2   state         4500 non-null   object
 3   season        4500 non-null   object
 4   mosquito_net  4500 non-null   object
 5   owns_tv       4500 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 211.1+ KB

In [100]:
df1nullvalues = df1.isnull().sum()
df1nullvalues

patient_id         0
age               47
state              0
season           772
mosquito_net     650
owns_tv         1437
dtype: int64

In [114]:
# Handling missing values
# Age → median imputation
df1['age'] = pd.to_numeric(df1['age'], errors='coerce')
df1['age'] = df1['age'].fillna(df1['age'].median())

In [116]:
# Fill categorical missing values with "Unknown"
categorical_cols = ['season', 'mosquito_net', 'owns_tv']

for col in categorical_cols:
    df1[col] = df1[col].fillna('Unknown')

In [120]:
# Final check
df1.isnull().sum()

patient_id      0
age             0
state           0
season          0
mosquito_net    0
owns_tv         0
dtype: int64

In [122]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    4500 non-null   int64
 1   age           4500 non-null   float64
 2   state         4500 non-null   object
 3   season        4500 non-null   object
 4   mosquito_net  4500 non-null   object
 5   owns_tv       4500 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 211.1+ KB

#### EXPLORATORY DATA ANALYSIS
---
The goal of EDA is to:

* understand the dataset structure
* identify trends and patterns
* detect anomalies
* generate healthcare insights
* prepare for machine learning
---

---

#### (1). Univariate Analysis (Analyzing one variable at a time)
* What is the age distribution?
* Which states appear most frequently?
* What proportion uses mosquito nets?
* Which season dominates?

---

#### (2). Bivariate Analysis (Analyzing relationships betwenn variables)
* Does mosquito net usage vary by state?
* Does season affect malaria positivity?
* Are younger patients more vulnerable?
* Do rainy periods correlate with higher cases?

---

#### (3). Multivariate Analysis (Studying multiple variable together)
* High-risk states during rainy seasons?
* Combined effect of age + mosquito net + season?
* Relationship between parasite count and reported cases?
---

In [135]:
df1.describe()

        patient_id          age
count  4500.000000  4500.000000
mean   3249.500000    40.053556
std    1299.182435    22.963698
min    1000.000000    -5.000000
25%    2124.750000    20.750000
50%    3249.500000    41.000000
75%    4374.250000    59.000000
max    5499.000000    79.000000

In [137]:
df1.describe(include='object')

         state season mosquito_net owns_tv
count     4500   4500         4500    4500
unique      36      3            3       3
top     Kaduna  Rainy           No     Yes
freq       299   2278         1927    1597